# Generated by Django 6.0.4 on 2026-04-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufc_fighters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fighter',
            old_name='created_ad',
            new_name='created_time',
        ),
        migrations.AddField(
            model_name='fighter',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
