# Generated by Django 6.0.4 on 2026-04-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufc_fighters', '0002_rename_created_ad_fighter_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
